/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FitStatusPanel.java
 *
 * Created on 16/07/2009, 10:19:32
 */

package tempo2;

/**
 *
 * @author kei041
 */
public class FitStatusPanel extends javax.swing.JPanel {

    /** Creates new form FitStatusPanel */
    public FitStatusPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jLabel1.setText("Post-fit RMS:");
        add(jLabel1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
