/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Tempo2Plot.java
 *
 * Created on 20/07/2009, 12:44:55
 */
package tempo2;

import java.awt.Point;
import java.awt.Rectangle;
import java.util.HashMap;
import ptolemy.plot.Plot;

/**
 *
 * @author kei041
 */
public class Tempo2Plot extends Plot {

    final private Tempo2Applet applet;

    /** Creates new form Tempo2Plot */
    public Tempo2Plot(Tempo2Applet applet) {
        super();
        initComponents();
        this.applet = applet;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickListener(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                keyPressListener(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                keyReleaseListener(evt);
            }
        });
        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 2, 2));
    }// </editor-fold>//GEN-END:initComponents

    private void clickListener(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickListener
        Point p = evt.getPoint();
        Rectangle frame = this.getBounds();
        double[] xrange = getXRange();
        double[] yrange = getYRange();

        //final double xposn = (p.getX()-35)/(frame.getWidth()-68)*(xrange[1]-xrange[0]) + xrange[0];
        //final double yposn = ((frame.getHeight() - p.getY()-35)/(frame.getHeight()-68))*(yrange[1]-yrange[0]) + yrange[0];
        final double xposn = getXPosn(p.getX());
        final double yposn = getYPosn(p.getY());

        if (applet.getControlPanel().positiveWrap()) {
            // +ve phase wrap
            this.applet.addPositiveWrap(xposn);

        }

        if (applet.getControlPanel().negativeWrap()) {
            // -ve phase wrap
            this.applet.addNegativeWrap(xposn);
        }

        if (applet.getControlPanel().clickStart()) {
            this.applet.setStart(xposn);
        }
        if (applet.getControlPanel().clickFinish()) {
            this.applet.setFinish(xposn);
        }




    }//GEN-LAST:event_clickListener

    private void keyPressListener(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_keyPressListener
    }//GEN-LAST:event_keyPressListener

    private void keyReleaseListener(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_keyReleaseListener
    }//GEN-LAST:event_keyReleaseListener

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
